#KLI-200 A, Bエリアで撮影した画像を競技システムに送信する
KatLab-MiyazakiUniv/etrobocon2024-camera-system pull request #8
Opened 2024-10-28 05:58 UTC by takahashitom

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- 競技システムに画像を送る処理を src/server/flask_server.py に追加
- 先鋭化処理を行うファイル src/image_processor.py を追加

2024-10-31 07:13 UTC, YKhm20020 approved these changes
LGTM出します。僕がいじっているところもないので、Approve 揃い次第マージしていい側です。
![LGTMoon 184523](https://github.com/user-attachments/assets/89bc7582-2724-4dd3-8782-18cdc490879d)

2024-11-04 02:29 UTC, CHIHAYATAKU requested changes

2024-11-04 02:29 UTC, CHIHAYATAKU commented on src/image_processor.py
> +    """CSVファイルをJSONファイルに変換するクラス."""
このコメントは合っていますか？
```suggestion
    """画像の先鋭化を行うクラス."""
```
とか？

2024-11-04 02:29 UTC, CHIHAYATAKU commented on src/image_processor.py
> +            return output_path
上の説明文のreturnと合わせるべき？
```suggestion
            return sharpened_image_path
```

2024-11-06 07:39 UTC, CHIHAYATAKU approved these changes
OKだと思います。
LGTMです。

2024-11-06 08:32 UTC, bizyutyu approved these changes
一部自分で追加したファイルあるけど、LGTM!
![LGTM](https://image.lgtmoon.dev/274496)

2024-11-06 08:49 UTC, merged